# Generated by Django 2.2.7 on 2019-12-27 04:44

#esta migracion es de datos para cargar los datos iniciales necesarios
from django.db import migrations


def create_proposal_status(apps, schema_editor):
    ProposalStatus = apps.get_model('managerApp', 'ProposalStatus')
    ProposalStatus.objects.create(name='Por evaluar')
    ProposalStatus.objects.create(name='Diferida')
    ProposalStatus.objects.create(name='Aprobada')
    ProposalStatus.objects.create(name='Rechazada')


def create_thesis_status(apps, schema_editor):
    ThesisStatus = apps.get_model('managerApp', 'ThesisStatus')
    ThesisStatus.objects.create(name='Por entregar')
    ThesisStatus.objects.create(name='Entregado y pendiente por defender')
    ThesisStatus.objects.create(name='Diferido')
    ThesisStatus.objects.create(name='Aprobado')
    ThesisStatus.objects.create(name='Aprobado con solicitud de correcciones')
    ThesisStatus.objects.create(name='Rechazado')


def create_terms(apps, schema_editor):
    Term = apps.get_model('managerApp','Term')
    Term.objects.create(id="201915", description='primer semestre del año académico')
    Term.objects.create(id="201925", description='segundo semestre del año académico')
    


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_proposal_status),
        migrations.RunPython(create_thesis_status),
        migrations.RunPython(create_terms)
    ]
