# Generated by Django 2.2.7 on 2020-01-08 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('managerApp', '0002_auto_20191229_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('document_id', models.IntegerField(db_index=True, verbose_name='cédula')),
                ('first_name_1', models.CharField(max_length=100, verbose_name='primer nombre')),
                ('first_name_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='segundo nombre')),
                ('last_name_1', models.CharField(max_length=100, verbose_name='primer apellido')),
                ('last_name_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='segundo apellido')),
                ('ucab_mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='correo ucab')),
                ('personal_mail', models.CharField(max_length=100, verbose_name='correo personal')),
                ('phone_1', models.CharField(max_length=15, verbose_name='teléfono 1')),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='teléfono 2')),
                ('observations', models.CharField(blank=True, max_length=500, null=True, verbose_name='observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='managerApp.PersonType', verbose_name='tipo de persona')),
            ],
            options={
                'verbose_name': 'historical Persona',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
